### ISSUE TITLE
lavastuff/init.lua:113: attempt to index local 'def' (a nil value)

### ISSUE THREAD

**Issue by Festus1965** [minetest-mods/lavastuff#19]
just happened
is version from d3a0da6/25.02.2022
but I didn't see solved issues this direction.

2023-02-10 21:01:58: ERROR[Main]:
 ServerError: AsyncErr: Lua: Runtime error from mod 'lavastuff' in callback item_OnPlace(): ../mods/lavastuff/init.lua:113: attempt to index local 'def' (a nil value)
stack traceback:
 	../mods/lavastuff/init.lua:113: in function </home/thomas/minetest/bin/../mods/lavastuff/init.lua:106>

I even take new version and see your result in this one.

**Comment by LoneWolfHT** [comment]
What were you doing when the crash was caused? I suspect another mod is using API functions incorrectly

You could try adding
```lua
if not def then minetest.log("error", "[lavastuff]: "..dump(pointed).." -|- "..dump(node)) return end
```
to line `112` if you want to temporarily fix the crash and send me info I could use to fix this

**Comment by Festus1965** [comment]
I have no idea who it has been, as at that time I am to bed - and sure all my local kids was off before
sure non of the advanced player as they report or ask what was wrong

lines now 121-123
				activate_func(user, node.name, def, pointed)
				if not def then minetest.log("error", "[lavastuff]: "..dump(pointed).." -|- "..dump(node)) return end
				COOLDOWN:set(user, 1)

but not restart yet, I will remember this and look if triggered and post then.

**Comment by LoneWolfHT** [comment]
That should be on line `112`, not `121`
![image](https://user-images.githubusercontent.com/28972859/219261037-673d2fe3-4586-43b5-9e85-60cdd4ecd282.png)

Sorry for the late reply

**Comment by SmallJoker** [comment]
d6d43a4828
